# Generated by Django 4.0.6 on 2022-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Проверен ли'),
        ),
    ]
