# Generated by Django 4.0.6 on 2022-10-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_comment_is_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя'),
        ),
    ]
