# Generated by Django 4.0.6 on 2022-10-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_comment_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='first_name',
            new_name='name',
        ),
    ]
