# Generated by Django 4.0.6 on 2022-10-03 14:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Keywords')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('text', tinymce.models.HTMLField(null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активировано')),
            ],
            options={
                'verbose_name': 'Информационная страница',
                'verbose_name_plural': 'Информационные страницы',
            },
        ),
    ]
