# Generated by Django 4.0.6 on 2022-10-13 14:57

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_globalsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsetting',
            name='main_text',
            field=tinymce.models.HTMLField(verbose_name='Текст на главной'),
        ),
    ]
